### ISSUE TITLE
Migrate openapi-diff artifacts to OpenAPITools (Maven & Docker)

### ISSUE THREAD

**Issue by joschi** [OpenAPITools/openapi-diff#165]
After this repository has been successfully moved to @OpenAPITools, we should make the artifacts available under the OpenAPITools name.

This includes the Maven artifacts (currently [`com.qdesrame`](https://search.maven.org/search?q=g:com.qdesrame) and [`com.github.joschi.openapi-diff`](https://search.maven.org/search?q=g:com.github.joschi.openapi-diff) and the Docker images (currently [`quen2404/openapi-diff`](https://hub.docker.com/r/quen2404/openapi-diff) and [`joschi/openapi-diff`](https://hub.docker.com/r/joschi/openapi-diff)).

- [x] Move Maven artifacts to [`org.openapitools.openapidiff`](https://search.maven.org/search?q=g:org.openapitools.openapidiff)
- [x] Move Docker images to [`openapitools`](https://hub.docker.com/u/openapitools)

**Comment by jmini** [comment]
About the maven coordinates, we had similar thoughts about the [OpenAPI Style Validator](https://github.com/OpenAPITools/openapi-style-validator) project. See corresponding issue: https://github.com/OpenAPITools/openapi-style-validator/issues/10

----

For the `groupId`, I think `org.openapitools.openapidiff` should be used.

For the `artifactId`, I would like to use a `openapi-diff-` prefix

----

Core:
```xml
  <groupId>org.openapitools.openapidiff</groupId>
  <artifactId>openapi-diff-core</artifactId>
```

Cli:
```xml
  <groupId>org.openapitools.openapidiff</groupId>
  <artifactId>openapi-diff-cli</artifactId>
```
For the `jar-with-dependencies` jar we are using the `all` classifier with the same coordinates.

Maven plugin (see issue: https://github.com/OpenAPITools/openapi-diff/issues/152):
```xml
  <groupId>org.openapitools.openapidiff</groupId>
  <artifactId>openapi-diff-maven-plugin</artifactId>
```

...

**Comment by joschi** [comment]
@quen2404 @jmini @wing328 After preparing the move to the suggested Maven coordinates, who would be able to set up the automation for releases to Maven Central and to the Docker Hub organization?

**Comment by jimschubert** [comment]
Why the recommendation for group `org.openapitools.openapidiff`? This means we would have to go through the entire onboarding process with Sonatype again. Can we just keep it `org.openapitools`?

**Comment by jimschubert** [comment]
> @quen2404 @jmini @wing328 After preparing the move to the suggested Maven coordinates, who would be able to set up the automation for releases to Maven Central and to the Docker Hub organization?

If we agree to change maven to `org.openapitools`, I can set these up. I unfortunately don't have enough bandwidth to work through onboarding another Maven project and managing separate creds.

**Comment by jimschubert** [comment]
I've setup https://hub.docker.com/repository/docker/openapitools/openapi-diff as an automated build:

* master ->`openapitools/openapi-diff:latest`
* Tag matching regex `/^[0-9]\.[0-9]\..*$/` ->`openapitools/openapi-diff:{tag}` where `{tag}` matches the tag being built

I've kicked off builds for each of the following 2.x tags, since the 1.x tags did not include a Dockerfile:

* 2.0.0-beta.1
* 2.0.0-beta.2
* 2.0.0-beta.3
* 2.0.0-beta.4

**Comment by joschi** [comment]
> Why the recommendation for group `org.openapitools.openapidiff`? This means we would have to go through the entire onboarding process with Sonatype again.

Accounts having permissions to publish artifacts in the group `com.example` on Sonatype OSSRH also have permissions to publish artifacts in any sub-group, for example `com.example.submodule1`.

**Comment by jimschubert** [comment]
> Accounts having permissions to publish artifacts in the group `com.example` on Sonatype OSSRH also have permissions to publish artifacts in any sub-group, for example `com.example.submodule1`.

Interesting. I probably knew this, but forgot. I guess `org.openapitools.openapidiff:openapi-diff` is good, but does seem a little redundant to me. I'll ping @wing328 for his opinion.

**Comment by wing328** [comment]
After reviewing the discussions, I'm also ok with either.

**Comment by joschi** [comment]
`org.openapitools.openapidiff` would be consistent with [`org.openapitools.empoa`](https://search.maven.org/search?q=g:org.openapitools.empoa) and [`org.openapitools.openapistylevalidator`](https://search.maven.org/search?q=g:org.openapitools.openapistylevalidator).

@jimschubert Ultimately it's up to you. We could try it with the regular credentials for Sonatype OSSRH which you mentioned and see if they are working with `org.openapitools.openapidiff`. 😉

**Comment by jimschubert** [comment]
@joschi Let's go with `org.openapitools.openapidiff`. I'm assuming we'd be releasing similar separate artifacts to the validator project:

* core library
* cli
* maven plugin
* gradle plugin

And it may make sense to have these all grouped under `org.openapitools.openapidiff` to avoid confusion with openapi-generator.

My initial hesitation was with regards to maintaining additional credentials, which isn't the case.

I see you have CircleCI and GitHub Workflows for building. I'd personally prefer using GitHub Workflows for build and deployment. Do you mind if we setup these releases in GitHub Workflows?

**Comment by joschi** [comment]
@jimschubert Thanks a lot!

GitHub workflows is fine for me.

**Comment by jimschubert** [comment]
@joschi I've setup the master, pr, and release workflows in #181 
The build workflow was using your GitHub action, which targets AdoptOpenJDK. I think we should use github's official action so we have the same for the Release workflow, otherwise there's a lot of manual setup we'd need to do. They're releasing support for AdoptOpenJDK in their v2 action.

**Comment by joschi** [comment]
> The build workflow was using your GitHub action, which targets AdoptOpenJDK. I think we should use github's official action so we have the same for the Release workflow, otherwise there's a lot of manual setup we'd need to do.

`joschi/setup-jdk` supports the same parameters as `actions/setup-java`. It's a drop-in replacement. 🤷

https://github.com/joschi/setup-jdk#publishing-using-apache-maven

**Comment by jimschubert** [comment]
I didn't mean to close this automatically when the pull request was merged.

[Pull Request check job](https://github.com/OpenAPITools/openapi-diff/runs/1250994613) and new [master build job](https://github.com/OpenAPITools/openapi-diff/actions/runs/305550123) look good. I only had to make a couple minor changes to these.

If you can double-check:
I _think_ all that's required now to publish to Sonatype/Maven Central Snapshot is to add `-P release` to the master build job's deploy task, but I couldn't find any existing release documentation. I didn't want to add this since I'm not familiar with some of the plugins here and I didn't want to inadvertently perform the 2.0.0 release.

Also:
There's an issue right now with Docker Automated Builds where it can't find the built artifact from the builder image. I haven't seen this happen before on Docker Hub, and there have already been two builds on master/latest through Docker Hub. I think it's a temporary hiccup because I've just retried a build and it's been in the pending state for 15 minutes, but we'll need to check back up on it tomorrow or so.

**Comment by joschi** [comment]
@jimschubert Thanks for all the effort!

I've picked up where you left and made the release workflow work and fixed the Docker build.

Here's the successful run for releasing openapi-diff 2.0.0-beta.5:
https://github.com/OpenAPITools/openapi-diff/runs/1252425534

**Comment by jimschubert** [comment]
Awesome. I wonder why the alpine base image decided to stop working.

Let me know if I can help out in any other ways.

**Comment by joschi** [comment]
> I wonder why the alpine base image decided to stop working.

The name of the shaded artifact (UberJAR) changed. So it was a totally self-inflicted breakage.

https://github.com/OpenAPITools/openapi-diff/commit/3a1ef030b68359886d91c8df90c7b063df5171b0#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L8-R8

**Comment by jimschubert** [comment]
> The name of the shaded artifact (UberJAR) changed. So it was a totally self-inflicted breakage.
> 
> [3a1ef03#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L8-R8](https://github.com/OpenAPITools/openapi-diff/commit/3a1ef030b68359886d91c8df90c7b063df5171b0#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L8-R8)

Ahh... I completely missed that the `cli-*-all` part of the glob was different from the original name. I tested locally and verified that the original name and the glob matched against my build outputs, but I guess I hadn't cleaned since the change.

**Comment by joschi** [comment]
With the release of openapi-diff 2.0.0-beta.6  (https://github.com/OpenAPITools/openapi-diff/runs/1273814348) with the correct Docker and Maven coordinates and the correct Java package names, I think we can close this issue.

Thanks @jimschubert, @jmini, @wing328, and @quen2404 for your support!
